site_name: My Brain Notes  # サイトのタイトル

# テーマ設定（人気のMaterialテーマを使う場合）
# ※使うには pip install mkdocs-material が必要です
theme:
  name: material
  language: ja           # 日本語化
  palette:
    scheme: default      # ライトモード
    primary: indigo      # メインカラー
    accent: indigo
  features:
    - search.suggest

plugins:
  - blog
      post_dir: blog/posts

# 左側のナビゲーションメニューを自動生成しない場合の設定（任意）
nav:
 - Home: index.md
 - Blog: blog/index.md
